spring.application.name=UTECharity_Project
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/charity_db
spring.datasource.username=root
spring.datasource.password=ohoangthien29@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
server.error.whitelabel.enabled=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.apache.commons.mail=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=odhthien29@gmail.com
spring.mail.password=xmrf aizu ftij ogyj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true




